apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: concert-runners
  namespace: actions-runner-system
spec:
  replicas: 2
  template:
    spec:
      repository: MorningMores/develop
      labels:
        - self-hosted
        - linux
        - x64
        - eks
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi