apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: concert-runners
  namespace: actions-runner-system
spec:
  replicas: 2
  template:
    spec:
      repository: MorningMores/develop
      labels:
        - self-hosted
        - linux
        - x64
        - eks
        - singapore
      image: summerwind/actions-runner:latest
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 1000m
          memory: 1Gi
      env:
        - name: RUNNER_WORKDIR
          value: /tmp/runner
      volumeMounts:
        - name: runner-work
          mountPath: /tmp/runner
      volumes:
        - name: runner-work
          emptyDir: {}