# Stage 1: Build
FROM maven:3.9.6-eclipse-temurin-17 AS build

WORKDIR /app

# copy pom.xml และดาวน์โหลด dependency ก่อน
COPY pom.xml .
RUN mvn dependency:go-offline

# copy source code และ build
COPY src ./src
RUN mvn clean package -DskipTests

# Stage 2: Run
FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

# copy jar มาจาก build stage
COPY --from=build /app/target/*.jar app.jar

EXPOSE 5000

ENTRYPOINT ["java","-jar","app.jar"]
