apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: concert-app
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: password
  MYSQL_DATABASE: concert_db
  MYSQL_USER: concert_user
  MYSQL_PASSWORD: concert_password
