apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: concert-app
data:
  init.sql: |
    -- This will be populated from database-setup.sql during deployment
    -- For now, we rely on Spring Boot's ddl-auto=update
    SELECT 'Database initialization delegated to Spring Boot' as status;
